name: ${project.artifactId}
description: ${project.description}
version: ${project.version}
api-version: 1.8
author: zPedroo_
main: com.zpedroo.voltzmining.VoltzMining
softdepend: [mcMMO]
depend: [FastAsyncWorldEdit, WorldGuard]
load: POSTWORLD