name: Mining
description: Only a simple mining plugin.
version: 1.0
api-version: 1.8
author: zPedroo_
main: com.zpedroo.voltzmining.VoltzMining
softdepend: [mcMMO]
depend: [FastAsyncWorldEdit, WorldGuard]
load: POSTWORLD